### ISSUE TITLE
Heroku Verbindung erstellen

### ISSUE THREAD

**Issue by SDouglas3** [ob-algdatii-ss19/leistungsnachweis-ateam#17]
Öffentliches Tool, das man mit Github verbinden kann, mit dem man das Projekt nach jedem erfolgreichen Push und Pass der Tests auf Heroku gebaut wird

**Comment by mountainflo** [comment]
Versuch mal mit Github-Webhooks eine Verbindung von Github zu Heroku herzustellen. Die Webhooks kannst du direkt über die Github-Repository-Settings hinzufügen
