### ISSUE TITLE
GO Graph-Objekt aus JSON erstellen und wieder zurückwandeln

### ISSUE THREAD

**Issue by mountainflo** [ob-algdatii-ss19/leistungsnachweis-ateam#20]
Im GO-Backend empfangene JSON-Daten werden geparst und am Ende wieder in JSON-Daten umgewandelt.

Das Frontend übergibt den Graph als JSON-Objekt an das Go-Backend. Im Backend werden die JSON-Daten geparst und anschließend wird daraus ein Graph-Objekt erstellt. Wenn die Algorithmen fertig sind, müssen aus dem Graph-Objekt wieder JSON-Daten erstellt werden.

**Comment by SDouglas3** [comment]
![grafik](https://user-images.githubusercontent.com/43849251/57215224-86709180-6fec-11e9-8826-1f526383cbf7.png)
Ein Adjazenzmatrixobjekt dieser Form benötigen wir für Issue #21
